### ISSUE TITLE
Applicant Info Not being logged

### ISSUE THREAD

**Issue by sammyanthag** [hacksu/2017-kenthackenough-ui-main#40]
When user is on a phone (so far Android phones have tested this)
they fully complete their application and their info doesn't show up on the staff site. Only their email is logged. 

I don't know if it's a DB issue or a staff site issue.

**Comment by NickCrawford** [comment]
@sammyanthag Could you list the steps to reproduce this bug?

**Comment by sammyanthag** [comment]
on an Android phone, apply for KHE (It was said at the top)

**Comment by NickCrawford** [comment]
I think this is all resolved now
